---
deployment:
  tasks:
    - export DEPLOYPATH=/home/adfb2574/public_html/adf_system
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R $(pwd)/* $DEPLOYPATH/
    - /bin/cp -R $(pwd)/.[^.]* $DEPLOYPATH/ 2>/dev/null || true
